[config]
gateway_name = "give me a name vro"
listens = ["0.0.0.0:54321"]
log_level = "info"

[[servers]]
name = "test"
downstream_hosts = ["0.0.0.0:54321"]

[[servers.locations]]
endpoint = "/"
proxy_pass = "http://192.168.1.103:8080"

[[servers.locations]]
endpoint = "/blehh"
proxy_pass = "http://192.168.1.103:8080"
