[config]
gateway_name = "give me a name vro"
listens = ["0.0.0.0:54321"]
log_level = "INFO"

[[servers]]
name = "test"
downstream_hosts = ["someaddress.com", "0.0.0.0:54321"]

[[servers.locations]]
endpoints = ["/", "/{*any}"]
proxy_passes = ["0.0.0.0:25025"]
health_check = true
health_check_frequency = 3000
