[config]
gateway_name = "give me a name vro"
listens = ["0.0.0.0:54321"]
log_level = "INFO"

[[servers]]
name = "test"

[[servers.downstream_hosts]]
Domain = "someaddress.com"

[[servers.locations]]
endpoints = ["/", "/{*any}"]
proxy_passes = ["192.168.1.103:8080"]
health_check = true
health_check_frequency = 3000
