[config]
gateway_name = "give me a name vro"
listens = ["0.0.0.0:54321"]
log_level = "INFO"

[[servers]]
name = "test"
downstream_hosts = ["someaddress.com", "0.0.0.0:54321"]

[servers.auth]
public_pem_http_url = "http://0.0.0.0:8989/public_pem"
check_duration = 360_000

[[servers.locations]]
endpoints = ["/auth", "/auth/{*any}"]
blacklisted_endpoints = ["/auth/public_pem"]
jwt_allowed_roles = ["user"]
requires_jwt = true
max_requests_per_sec = 10
proxy_passes = ["0.0.0.0:8989"]
health_check = true
health_check_frequency = 3000
