[config]
gateway_name = "give me a name vro"
listens = ["0.0.0.0:54321"]
log_level = "DEBUG"

[[servers]]
name = "test"
downstream_hosts = ["someaddress.com", "0.0.0.0:54321", "127.0.0.1:54321"]

# [servers.auth]
# public_pem_http_url = "http://0.0.0.0:25025/public_pem"
# check_duration = 10000

# [servers.cache]
# url = "redis://0.0.0.0:6379"

[[servers.locations]]
# blacklisted_endpoints = ["/auth/public_pem"]
max_requests_per_sec = 10
proxy_passes = ["0.0.0.0:8989"]
# health_check = true
# health_check_frequency = 3000
# requires_jwt = true
# cacheable = true
# cache_time_secs = 3600
# jwt_allowed_roles = ["user"]

[[servers.locations.endpoints]]
path = "/"
reroute = "/"

[[servers.locations.endpoints]]
path = "/{*any}"
reroute = "/mazil/{*any}"
